### ISSUE TITLE
Preferred approach for xSPInstallPrereqs

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#102]
This is a follow on discussion that was started in relation to issue #100 - the issue to be discussed is whether or not the prerequisite installer that ships with SharePoint is the desired approach to install the prereqs, and whether or not the approaches to detecting if they are installed in the test method is enough. 

This stems back to some issues being reported around the prereq installer getting caught in a reboot loop on the machine, which was identified due to the fact that there was a reboot line on a return code of 0 from the prereq installer, but the reason it kept trying to run it is that the test method must still have been returning false where it should have been returning true - which represents a bug in how it determines what is installed.

So the questions to answer here:

1. Should we continue to use the prerequisite installer or should we script a manual install
2. Are people who are running the prereq installer and seeing the reboot loop able to help identify what components that it thinks are not installed so we can patch this up? (I've been unable to replicate this in my labs which is making it harder for me)

**Comment by HiltonGiesenow** [comment]
I'm a bit in two minds about this. I'm worried there's more happening in the prereq.exe than might immediately be obvious, but that's probably the only real concern. Aside from that, going this new route gives a chance to approach it differently. For instance, it -might- be useful to pass separate exe paths (as it works now), but in practice we're likely to have all of these pre-reqs in the same folder - just a folder path could be sufficient. Does anyone do it differently?

In addition, perhaps a "download all prerequs" step could be useful to make a multi-farm install into a "Download once then always run 'offline'" install, if you get what I mean? If so, we could possibly even split this into a "SPDownloadPrereqs" resource as well as a "xSPInstallPrereqs" resource. The first machine this runs on would do the download, the rest would have a check to not download if they exist already, and therefore simply consume.

Thoughts?

As further info - on my side it was failing because the path was incorrect to the prerequs themselves (I'd basically copy pasted an error). The installer exited ok, but it showed a link to the error log. If we choose to continue using the prereqinstaller.exe, we could look if there's a way to better query for error logs or errors in those logs

**Comment by HiltonGiesenow** [comment]
By the way, @BrianFarnhill  sent me some code to help with this - posting here in case it's useful (thanks @BrianFarnhill !)

$WindowsFeatures = Get-WindowsFeature -Name Net-Framework-Features,Web-Server,Web-WebServer,Web-Common-Http,Web-Static-Content,Web-Default-Doc,Web-Dir-Browsing,Web-Http-Errors,Web-App-Dev,Web-Asp-Net,Web-Net-Ext,Web-ISAPI-Ext,Web-ISAPI-Filter,Web-Health,Web-Http-Logging,Web-Log-Libraries,Web-Request-Monitor,Web-Http-Tracing,Web-Security,Web-Basic-Auth,Web-Windows-Auth,Web-Filtering,Web-Digest-Auth,Web-Performance,Web-Stat-Compression,Web-Dyn-Compression,Web-Mgmt-Tools,Web-Mgmt-Console,Web-Mgmt-Compat,Web-Metabase,Application-Server,AS-Web-Support,AS-TCP-Port-Sharing,AS-WAS-Support, AS-HTTP-Activation,AS-TCP-Activation,AS-Named-Pipes,AS-Net-Framework,WAS,WAS-Process-Model,WAS-NET-Environment,WAS-Config-APIs,Web-Lgcy-Scripting,Windows-Identity-Foundation,Server-Media-Foundation,Xps-Viewer
 
    $returnValue = @{}
        foreach ($feature in $WindowsFeatures) {
        $returnValue.Add($feature.Name, $feature.Installed)
    }
 
        $installedItems = Get-CimInstance -ClassName Win32_Product
   
    #Common prereqs
    $returnValue.Add("Microsoft Identity Extensions", (@(Get-ChildItem HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\ -Recurse | ? {$_.GetValue("DisplayName") -eq "Microsoft Identity Extensions" }).Count -gt 0))
    $returnValue.Add("Microsoft CCR and DSS Runtime 2008 R3", (($installedItems | ? {$_.Name -eq "Microsoft CCR and DSS Runtime 2008 R3"}) -ne $null))
    $returnValue.Add("Microsoft Sync Framework Runtime v1.0 SP1 (x64)", (($installedItems | ? {$_.Name -eq "Microsoft Sync Framework Runtime v1.0 SP1 (x64)"}) -ne $null))
    $returnValue.Add("AppFabric 1.1 for Windows Server", (($installedItems | ? {$_.Name -eq "AppFabric 1.1 for Windows Server"}) -ne $null))
    $returnValue.Add("WCF Data Services 5.6.0 Runtime", (($installedItems | ? {$_.Name -eq "WCF Data Services 5.6.0 Runtime"}) -ne $null))
    $returnValue.Add("WCF Data Services 5.0 (for OData v3) Primary Components", (($installedItems | ? {$_.Name -eq "WCF Data Services 5.0 (for OData v3) Primary Components"}) -ne $null))
    $returnValue.Add("Microsoft SQL Server 2008 R2 Native Client", (($installedItems | ? {$_.Name -eq "Microsoft SQL Server 2008 R2 Native Client"}) -ne $null))
    $returnValue.Add("Active Directory Rights Management Services Client 2.0", (($installedItems | ? {$_.Name -eq "Active Directory Rights Management Services Client 2.0"}) -ne $null))
 
        $returnValue

**Comment by BrianFarnhill** [comment]
@HiltonGiesenow Well we know where the prereq installer logs end up (in the temp folder) ... there shouldn't be anything to stop us from interrogating the log matching the time that the installer was started and use that to determine if there is an actual error even when the return code is a 0, which means we can at least throw a meaningful error in that case. Is this worth pursuing do we think?

**Comment by BrianFarnhill** [comment]
@HiltonGiesenow Just noting that the script I gave you there is specifically for SharePoint 2013 - if anyone sees the issue for SharePoint 2016 and wants to test that you'll need to modify the list. But seeing as people are seeing this with 2013 on Server 2012 R2 I would like to resolve it there first.

**Comment by HiltonGiesenow** [comment]
Yup, exactly what I had in mind, we just need to make sure we're getting exactly the right file, parsing the log properly, etc. Nothing rocket-science-y, just a bit of work to get it all right.

**Comment by NikCharlebois** [comment]
The problem seems to be coming from the C++ installs. The Get-TargetResource is the culprit. Here is the result of my Hashtable

key = Web-WebServer , value = True
key = Web-WMI , value = True
key = Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005 , value = False
key = WAS-Process-Model , value = True
key = Web-Health , value = True
key = Web-Client-Auth , value = True
key = Microsoft SQL Server 2012 Native Client , value = True
key = Windows-Identity-Foundation , value = True
key = Web-Stat-Compression , value = True
key = PowerShell-V2 , value = True
key = NET-Framework-45-ASPNET , value = True
key = Active Directory Rights Management Services Client 2.1 , value = True
key = WAS-NET-Environment , value = True
key = Web-Lgcy-Mgmt-Console , value = True
key = NET-Framework-Core , value = True
key = NET-Non-HTTP-Activ , value = True
key = Web-ISAPI-Ext , value = True
key = Web-Log-Libraries , value = True
key = Application-Server , value = True
key = Web-Scripting-Tools , value = True
key = Web-Lgcy-Scripting , value = True
key = Web-Http-Logging , value = True
key = NET-WCF-HTTP-Activation45 , value = True
key = Microsoft CCR and DSS Runtime 2008 R3 , value = True
key = Microsoft ODBC Driver 11 for SQL Server , value = True
key = Web-Dir-Browsing , value = True
key = Web-Http-Errors , value = True
key = AS-Web-Support , value = True
key = Microsoft Sync Framework Runtime v1.0 SP1 (x64) , value = True
key = Web-Basic-Auth , value = True
key = Web-Performance , value = True
key = Web-Digest-Auth , value = True
key = NET-Framework-Features , value = True
key = Web-Dyn-Compression , value = True
key = WAS-Config-APIs , value = True
key = Web-Metabase , value = True
key = Web-Security , value = True
key = WCF Data Services 5.6.0 Runtime , value = True
key = Web-App-Dev , value = True
key = Web-Windows-Auth , value = True
key = AppFabric 1.1 for Windows Server , value = True
key = Web-Default-Doc , value = True
key = Web-Url-Auth , value = True
key = Web-ISAPI-Filter , value = True
key = Web-Cert-Auth , value = True
key = Web-Net-Ext45 , value = True
key = AS-NET-Framework , value = True
key = Web-Request-Monitor , value = True
key = Web-Mgmt-Tools , value = True
key = Web-Filtering , value = True
key = Web-Static-Content , value = True
key = Web-Mgmt-Console , value = True
key = Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005 , value = False
key = Web-Net-Ext , value = True
key = WAS, value = True
key = NET-HTTP-Activation , value = True
key = Web-Common-Http , value = True
key = Web-Mgmt-Compat , value = True
key = Web-Http-Redirect , value = True
key = Web-Asp-Net45 , value = True
key = Web-Server , value = True
key = Web-IP-Security , value = True
key = Microsoft Identity Extensions , value = True

**Comment by NikCharlebois** [comment]
Ok, so I've found the error. We are looking for 
Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.21005
Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.21005

Whereas my Windows Server 2012 R2 server has the following installed:
Microsoft Visual C++ 2015 x64 Minimum Runtime - 14.0.23026
Microsoft Visual C++ 2015 x64 Additional Runtime - 14.0.23026

In the Get-TargetResource method, we need to add and OR operator that would set the value to true if either is present.

**Comment by HiltonGiesenow** [comment]
Hey Nik,

Thanks for tracking this down, let's definitely fix.

What do you think about the broader discussion about this though - rewriting to exclude prerequinstaller.exe altogether?

**Comment by NikCharlebois** [comment]
@HiltonGiesenow I'm not a big fan of reinventing the wheel. What would be the pros of doing this? I am afraid things will slip through the cracks as Microsoft releases CUs.

**Comment by HiltonGiesenow** [comment]
I've also got concerns, but I think the advantage is we don't have to rely on this installer as much - from the looks of what it does (black box) everything's pretty easy to do with DSC natively, and we don't need to fiddle with logs / interpret return codes / etc. What would you see as pros versus cons to this? I'm worried we'll keep getting issues like the ones you just fixed.

**Comment by BrianFarnhill** [comment]
@NikCharlebois That prereq is on our 2016 list, so that might not be related to the looping people are seeing on 2013 as well but this might explain the looping on 2016 so I'll make a quick patch to get that one sorted (just wanna confirm my lab is seeing it as well - I think my lab was running the IT Pro preview and not beta 2 so I'll fix that)

**Comment by XdrXdr77** [comment]
Hi @ all,

i´m spending a lot of time by testing the Installation of SP2013 and SP2016 with DSC. I think it is a very good alternative against the AutoSPInstaller, but ...... 

..... the reboot handling didn´t work in my case. I´ve tested the xPendingReboot Module. No way to get an reboot. Only if i modify the LCM, but this ends in a reboot loop.

.... the resume of the configuration starts in the background if i manually rebooted the Server after installing the PreReq and Binaries. Is there a way to see whats happen an when the configuration is finished. A Log FIle would be nice too. I can only check the log files in the Temp Folder during and after the installtion of PReReq and binaries if it is finshed.

Can you tell me what you are using for a system configuration of your test envrionment.
I´m using a WIndows Server 2012R2 for SharePoint and Server 2016 TP2 for DC and SQL. The SQL Server is also the 2016 TP. Which additional features do you have activated and installed ?

Kind Regards

A.S.

**Comment by BrianFarnhill** [comment]
Hey A.S. @XdrXdr77 

So the LCM is the way to get the reboots to work, you should have to specify AllowReboot = true in your configuration and that will generate the .meta.mof file which can configure the LCM for you to do this. Then the DSC resources we have will tell the LCM when it needs the reboot.

In regards to the looping, this should all be resolved for both 2013 and 2016 on Server 2012 R2. There has been no work done yet to add support for the Server 2016 TP though, so it more than likely will not work. 

What version are you using? I know most of the fixes for the reboot looping we did recently are in v0.9 which is still pending release (catching up after the holiday break) so if you aren't using what's in the dev branch (or in the releasev0.9 branch) then grab that first and see how it goes.

**Comment by BrianFarnhill** [comment]
So after catching up on this one, it appears the issues that were raised re:looping on the prereq check have been sorted. After discussions here and within my core team as well, the choice around "should we use the prerequisiteinstaller.exe to install things or do it by hand" is going to be that we'll keep using the prerequisite installer. That way if/when it gets changed in a service pack release (think back to the patched version of it that added support for server 2012 R2 with service pack 1 of 2013 came out) we will get whatever changes are in there automatically. I'm still all ears for better approaches to determining whether or not everything is installed for our get method, but for the time being I'm happy to close this specific discussion off.
