### ISSUE TITLE
Out-File Logging inside each module

### ISSUE THREAD

**Issue by dwilkes** [PowerShell/xSharePoint#218]
Please look to add  a utility that will write to a log file from within each "function" in a module. Looking to get Verbose logging out to a file. High Importance!

Derek Wilkes - General Motors

**Comment by BrianFarnhill** [comment]
Hi Derek,

This idea was thrown around when we were in the early planning stages but it was decided that we would park it, as realistically we would need something more generic that would work across all DSC resources and not just xSharePoint. That said though, there are ways that you can look to capture the output yourself. If you ever go and have a look at how we use the DSC extension in Azure for virtual machines, it actually logs the output to a text file when it executes the configuration every time the VM boots, so we could look to do something similar to this to capture the output of the entire process. What we want to do here is to make use of a feature called "[Redirection](https://technet.microsoft.com/en-us/library/hh847746.aspx)" in PowerShell. We can use that to tell PowerShell to send the output to a specific text file.

    Start-DscConfiguration [standard parameters here] *> C:\output.txt

The *> operator will redirect all output to that text file. So now if we take that concept and apply it so that we capture each DSC run we just need to implement things for the local configuration manager a little differently. Instead of letting the LCM do things run its check every 30 minutes we instead tell it to do nothing, and you can then add a scheduled task to each server to run a PowerShell script which will call the commands needed to start your configuration and output the verbose output to the specified text file. This way you can do things like calculate the appropriate file name to log to for each run and then tell it to begin its configuration. 

Let me know if your happy with that approach and we can close this issue off.

 \- B

**Comment by tonyhxh** [comment]
Brian:

I am not sure it's a good idea to change the default behavior of the pull method. Could you let me know why in the DSC resource modules, you didn't use OOTB log module to dump the verbose log to analytic/debug event log?

Thanks
Tony Huang from GM

**Comment by BrianFarnhill** [comment]
Hi @tonyhxh - typically we don't see customers wanting to log every single action DSC attempts, only when things don't work and you're in a troubleshooting scenario, so the out of the box logging to the windows event log that shows when a configuration started and completed, as well as the compliance server reporting from using a pull server is generally enough.

What I've proposed there isn't changing the default behavior of the pull method - you can still use a pull server and it behaves exactly the same (and will still report its status to the compliance server), all you are controlling here is the scheduling, and this approach actually gives you more control over the exact scheduling, not just the interval.

If that still doesn't meet your requirements, you can also use the [xDscDiagnostics](https://github.com/PowerShell/xDscDiagnostics) module to get to the verbose output from individual DSC operations (using Get-DscOperation and Trace-xDscOperation). This can be scheduled in a scheduled task on the server (or even centrally, it doesn't need to execute on the server directly) and you can use it to gather the output and put it to text files as you need to do so.

To specifically answer your question, the reasons we haven't and do not plan to build any additional logging in to the modules themselves:

* Between the windows event logs and compliance server reporting most customers don't need it
* The ones who do can use either of the two approaches I've mentioned above to get verbose output in a manner which is not dependent on individual DSC resources doing this

Given the alternatives which will automatically work with all other DSC resources (including any custom ones that people write as well as those published through the PowerShell gallery) there was not any need that was seen to add additional logging to the resource individually as this would be more effort for what is essentially little to no benefit given the existing available options.

**Comment by tonyhxh** [comment]
It seems to me that under C:\windows\System32\Configuration\ConfigurationStatus on each node, the *.details.json files contains the verbose log already. 

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
@tonyhxh This is true for PowerShell 5, and it will recycle some of these logs as well - so if you need to retain them for any period of time make sure you copy them elsewhere.

Based on the discussion and alternative logging options, I'm going to close this issue off. Thanks guys.
