### ISSUE TITLE
web.config modification

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/xSharePoint#219]
Is there a plan to create a resource module to update web.config of web apps?

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
For settings that go to the "AppSettings" part of the config file, you can use [xWebConfigKeyValue](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1) from [xWebAdministration](https://github.com/PowerShell/xWebAdministration) to do this. For more complex modifications, we have thrown some ideas around about how to tackle this and whether or not they should be in xSharePoint or xWebAdministration. Is there a specific type of modification you want to make?

**Comment by tonyhxh** [comment]
I was mainly talking about SPWebConfigModification which can apply changes to every node at one time. 

I guess xWebAdministration probably can do the job. thanks a lot.

**Comment by BrianFarnhill** [comment]
The problem with SPWebConfigModification is that you will find that it won't enforce a desired state as well as DSC would when someone makes manual changes to a web.config file after the SPWebConfigModification class applies its changes. So if you are going to be changing web.config files, I would look in to what xWebAdministration can do and whether or not that needs extending. I'm closing this one off, thanks @tonyhxh

**Comment by ykuijs** [comment]
The issue with the xWebAdministration module is that it uses the IIS to change the web.config. However SharePoint settings are changed by SharePoint itself and are therefore not known to IIS. So you cannot change all settings in the web.config via IIS.

I tested this earlier via appcmd:
When running “appcmd list config acme /section:system.web/customErrors”, appcmd returns the following output:
<system.web>
  <customErrors mode="On">
  </customErrors>
</system.web>
This is fine and exactly what is in the web.config. If I change it to Off and then run the command again, appcmd returns off.

However if I then try a SharePoint setting like “appcmd list config acme /section:SharePoint/BlobCache”, appcmd returns the following message:
ERROR ( message:Unknown config section "SharePoint/BlobCache".  Replace with ? for help. )
The same goes for all entries in the SharePoint section, so the CallStack can’t be changed this way.

Therefore you need to do this either via SharePoint (SPWebConfigModifications, but with the issues mentioned by Brian) or directly on the XML file. In the latter case, you would have to do this change on each of the servers that is running the Web Application role in order to keep the web.config files in sync.

**Comment by BrianFarnhill** [comment]
@ykuijs I would be leaning towards doing it directly in the XML, as it would then maintain desired state more accurately afterwards by watching the actual file, as opposed to ensure that an spwebconfigmodification exists because that won't track that a change has been manually made to the file (it will reapply when other automated changes that SharePoint is aware of are made, but it won't stop manual intervention with the file directly). So I don't want to set the wrong expectation that xSharePoint is controlling the desired state of the config file, when it's not really directly doing that. I feel like something that manipulates the file directly (without appcmd's involvement) that is made generic enough for the entire config file would be more at home in xWebAdministration than in xSharePoint.

**Comment by ykuijs** [comment]
@BrianFarnhill Agree, this does however mean we:
- Create a resource that changes it on the local server and the user of the resource has to create a config for all servers with the web application role. This might not be real user friendly. 
or
- Create a resource that changes it on all servers, but that means we have to: Request the server list from the ConfigDB, connect to all servers via SMB or Remote Powershell (assuming this is not prevented e.g. by a firewall) and change the web.config on all servers. This can become quite complex.

**Comment by BrianFarnhill** [comment]
@ykuijs Looping back on this one - in regards to your options, the first one actually does make sense because we should already have a config for all servers that have the web app role anyway for things like SSL bindings through xWebSite, for service instances that run on them through xSPServiceInstance and other things that are specific to an individual server - so I don't think we are introducing something new here in terms of a new config for that role specifically. I am extremely hesitant to create a resource that will change them all from one server as it would take longer to run and have more moving parts, where as a local one could change the file quite quickly.

**Comment by MikeLacher448** [comment]
While I can see the concern of using the SharePoint webconfigmodification methods not truly enforcing the state of the web.config file if it is manually edited, or changed through another method, I've always followed the practice of "thou shall not edit web.config files" and used the webconfigmodification method of the web application for SharePoint to push those changes out. I'm kinda torn on this one at the moment.

**Comment by ykuijs** [comment]
Agree with your comment @MikeLacher448, over the past years I have pushed many developers towards using the WebConfigModifications class. The reasons behind this was first consistency, I have seen many environments where server1 would have different settings then server2, etc. Second, preventing manual changes (which may lead to the first issue). Many installation instructions contained manual steps for changing the web.config.
The WebConfigModifications class solved both of these issues.

However from that perspective: This DSC resource does exactly the same as the WebConfigModifications class: It prevents manual actions and makes sure the settings are configured the way you want them to be. Even better: If you manually change the XML, the DSC resource detects and corrects this, where the WebConfigModifications class doesn't.

The only "risk" I see is that the config isn't targeted to all WFE servers in the farm, which can cause inconsistent settings between different servers. So we have document this really well in our documentation, so our users are aware.

**Comment by MikeLacher448** [comment]
any concerns with SharePoint pushing a config, that the DSC config is not aware of, and getting stuck in a loop of SharePoint updating web.config, DSC reverting it, etc.. ?

**Comment by BrianFarnhill** [comment]
Just had a chat about this with my core architecture/planning guys for this, and they both tend to agree that we should avoid SPWebConfigModification because it wont enforce the desired state in the config file themselves and it has a history of being unreliable.

As @ykuijs stated above the DSC resource will ensure the XML files always match the desired state and automates the changes for consistency, so if the only concern is making sure we tell everyone that you need to apply the settings to every server, then lets make sure we put that in the doco (in our schema.mof doco so it hits the PowerShell module and the wiki doco) and make sure the example for the small farm matches how it should be done as well. 

@MikeLacher448 in regards to concerns about SharePoint pushing a config that the DSC is not aware of and us getting stuck in a "loop" yes this could happen in theory, but I don't think it's something that would happen as a common scenario. I can't think of something where SharePoint would be pushing a configuration to the web.configs that you would override with DSC on a regular basis - maybe if you have some devs that aren't talking to the IT pros about how the config should be done, but I can't think of any specific things that would be different. Can you think of a specific scenario here that would warrant taking a different approach or doing something different with it?

**Comment by ykuijs** [comment]
The way the WebConfigModifications class works is it only pushes changes to the web.config file once. Either when a new WebConfigModification is added or when the WFE role is added to a (new) server, essentially creating a fresh web.config file. It won't monitor the web.config file after that.

So even when you change something using the WebConfigModifications method which conflicts with the DSC state, DSC will change it back to the desired state after which SharePoint won't bother with it anymore. So you never end up in a loop.

**Comment by MikeLacher448** [comment]
I've seen the changes registered in the WebConfigModifications get pushed out when you make other changes to the SharePoint web application settings, and sometimes after patching.
I guess the main thing is having the resource that is editing the web.config work so that it only cares about the change it made. For example, with the blob cache, the resource would need to only test that the changes required for blob cache are present, and not fail if another part of the web.config has been modified since the last update.
