### ISSUE TITLE
xInstallPrerequisite

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/xSharePoint#229]
Just a little feedback regarding to prerequisite install. I only made this far on my test environment today. :) 

The latest RTM bits seems to have something new with prerequisites. 

I had to replace "DotNet452" with "DotNetFx" in MSFT_xSPInstallPrereqs.psm1 and MSFT_xSPInstallPrereqs.schema.mof. Also had to delete "$KB2898850" from $requireParams.

if ($majorVersion -eq 16) {
        Write-Verbose -Message "Version: SharePoint 2016"
        $requiredParams = @("SQLNCli","Sync","AppFabric","IDFX11","MSIPCClient","KB3092423","WCFDataServices56","MSVCRT11","MSVCRT14","ODBC","DotNetFx")
}

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
@tonyhxh Looks like the prereq installer changed in the RTM build. I'll flag this to be fixed ASAP. Thanks for reporting it

**Comment by camiloborges** [comment]
@BrianFarnhill - wouldn't it be easier for us to have the pre-reqs as a
list based on the version and build? It isn't the first time we need to
change this in the past couple of months :)

That said, Achieving so would mean an complete re-write of the module so
I'd be tempted to just update it for now but have a commitment from all of
us to address this limitation/concern at a later stage.

**Comment by BrianFarnhill** [comment]
@camiloborges Yes and no - we essentially have that now in the list of prereqs that it checks for based on major build version (15/16). We don't really need to go to the build version below that because the prereq installer doesn't normally change in builds, the only potential change point is for service packs (a CU doesn't patch the files you use to install, just the installation itself) so I think managing the list how we are currently isn't an awful approach - but I'm open to looking at how we structure it to make the prereqs more fluid as opposed to the hardcoding that happens now.

**Comment by BrianFarnhill** [comment]
@tonyhxh I just checked in the code to fix this in #279 - I'll close this off once it makes it to the dev branch

**Comment by BrianFarnhill** [comment]
All done - thanks for reporting @tonyhxh

**Comment by rbraun95** [comment]
@BrianFarnhill, @tonyhxh Are there any SP2019 versions  of MSFT_SPInstallPrereqs.psm1 and MSFT_SPInstallPrereqs.schema?  The TAP bits have DotNet47 instead of DotNetFx for the prereq installer argument list.

**Comment by rbraun95** [comment]
Understood.  I will remove my comment for now.
