### ISSUE TITLE
InstallAccount as Mandatory Parameter

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/xSharePoint#237]
It looks like InstallAccount should be a Mandatory Parameter on resource module xSPJoinFarm, xSPCreateFarm, and xSPManagementAccount, otherwise test-dscconfiguration would fail. 

Thanks
Tony Huang

**Comment by BrianFarnhill** [comment]
Hi @tonyhxh 

This is not the case - have a read of our [documentation on the InstallAccount parameter](https://github.com/PowerShell/xSharePoint/wiki/Remote%20sessions%20and%20the%20InstallAccount%20variable).

If you try to run any resource at all (with the exception of xSPInstall and xSPInstallBinaries) and do not provide InstallAccount or PsDscRunAsCredential (the second one there only being available in PowerShell 5) then you will be given an error when it runs that tells you that you need to do one of those for the resource to work correctly. The reason it's not a mandatory parameter is that for PowerShell 5 we don't want people to have to specify InstallAccount as it should not be used any more where WMF5 is installed, so we make it optional and thrown the error when it's not provided.

Closing this one off now.

 \- B

**Comment by tonyhxh** [comment]
We gave PsDscRunAsCredential, but not InstallAccount, so the push seems fine, however when we tried to do test-dscconfiguration from the push server, it always fail because installAccount is optional but it seems to be hard-coded in the get methods of xSPJoinFarm, xSPCreateFarm, and xSPManagementAccount. 

Thanks
Tony

**Comment by BrianFarnhill** [comment]
@tonyhxh We don't check InstallAccount in our test methods, we check specific properties in each of those test methods:

xSPCreateFarm and xSPJoinFarm:

     return Test-xSharePointSpecificParameters -CurrentValues $CurrentValues -DesiredValues $PSBoundParameters -ValuesToCheck @("FarmConfigDatabaseName")

xSPManagedAccount:

     return Test-xSharePointSpecificParameters -CurrentValues $CurrentValues -DesiredValues $PSBoundParameters -ValuesToCheck @("AccountName", "Schedule","PreExpireDays","EmailNotification") 

So if you are seeing a fail on those resources from Test-DscConfiguration then you could be seeing a fault in the logic somewhere around the properties we do check. I would suggest as a starting point that you check the output from the Get method on each to see if it is returning the values you expect:

    Import-Module "C:\program files\WindowsPowerShell\Modules\xSharePoint\DSCResources\MSFT_xSPCreateFarm\MSFT_xSPCreateFarm.psm1"
    Get-TargetResource [Add parameters here]

This will show you the values we detect from that module (just substitute in the modules you want to check on that import module line, best to use a new window for each to be sure there is nothing hanging around on each test) and then compare those to what is in your config. This should shine a light on why the test method is failing - but I can definitely tell you it won't be because of the InstallAccount. 

If you find issues with specific resources failing a test when they should pass we can open issues for each of those and move forward to resolve.
