### ISSUE TITLE
Create a Web Application in an existing App Pool

### ISSUE THREAD

**Issue by alarzi** [PowerShell/xSharePoint#268]
Hey @BrianFarnhill,

In the module MSFT_xSPWebApplication, $ApplicationPoolAccount is mandatory, which prevent us to create a new web application in an existing application pool.
Maybe the code should also be updated to pass the ApplicationPoolAccount parameter to the New-SPWebApplication cmdlet only if it is specified.

Many thanks for your great job!

**Comment by BrianFarnhill** [comment]
Hey @alarzi - It's mandatory because we strive to make the resources as idempotent as possible, which means when we run xSPWebApplication we can't assume that the app pool will already exist, so it can be provisioned if it needs to be, or it can be ignored if it is set. 

@caadam @anlynes - Your opinions on this one guys?

**Comment by ykuijs** [comment]
The New-SPWebApplication supports creating new web applications in existing application pools. If you specify the ApplicationPool parameter without the ApplicationPoolAccount parameter, SharePoint assumes that the application pool already exists. So we could change the resource to first check if the application pool exists and if so, leave out the ApplicationPoolAccount parameter.

**Comment by camiloborges** [comment]
Interesting concern.

I am taking into account your point here Brian.
I think the answer to this depends on few things: 
1) what do we have as standard everywhere else? I am not sure we are 100% consistent on this one.
2) DSC idea really is to have 1 definition file that defines the entire farm, so in this case, does it make a difference having one way or the other? It feels order is more important, which then means you have these as optionals
3) if we don't have it consistent everywhere else I believe we should raise a technical debt issue and track it there. I am not fussed with having as optional or mandatory. I care about consistency :)

**Comment by BrianFarnhill** [comment]
@camiloborges Where are we not consistent with this? I can't think of anywhere but if there is, I agree we should track them as technical debt and bring them in line. 

In terms of "1 definition for the entire farm" I don't think that is entirely true - what I want is resources that are idempotent, and if they are part of a configuration for a whole farm thats great, but if the farm is only partially done by DSC that's fine too. To get the resources to be idempotent though we need to take in any parameter that "could" be needed to get to the desired state. In the context of "I've written a config for the whole farm so I know the app pool already exists" that then says you should be able to work without passing app pool credentials to xSPWebApplication because you know it will exist from elsewhere. But in the context of "I want a web app and I don't care what state the farm is in currently" (which I'll add is where we want our resources to be, and I openly acknowledge some of the older resources aren't there yet) you should have to pass the credential because it "could" be needed to create the app pool when it does the web app.

**Comment by camiloborges** [comment]
All fair points.
Are we not consistent: I am not sure TBH. I think we are. But it might be worth checking just to be sure.

I am ok and agree with your points(I did think you always wanted it to be all farm or nothing but that is a different point). But now... How do we make sure people are always understand this is the case? Should we include some of what you are saying here in the documentation?

**Comment by ykuijs** [comment]
Isn't it an option to facilitate both options:
1. If the specified application pool exists, use that by not specifying the applicationpoolaccount
2. If the specified application pool doesn't exist, specify the applicationpoolaccount and create it

That way we enable both scenario's and are idempotent.

**Comment by BrianFarnhill** [comment]
@ykuijs Are you talking about what we do within the resource? As in how we call New-SPWebApplication in the set method? I'm neither here nor there on what we do with that, but the schema for the DSC resource will still need to have the app pool account as a required field in case it has to create it like I was explaining above?

**Comment by ykuijs** [comment]
@BrianFarnhill That is correct. I reviewed the code and currently we are not checking the existence of the application pool, but always adding the applicationpoolaccount parameter essentially trying to create a new application pool.

I agree that the schema should not be changed.

**Comment by BrianFarnhill** [comment]
@ykuijs Does this make a difference though? If you pass the app pool name and credential again and it matches what is already there, there is no exception or anything as far as I'm aware?

**Comment by ykuijs** [comment]
The description on TechNet led me to believe that when you specify the ApplicationPoolAccount parameter, the cmdlet assumes a new application pool had to be created. Will perform some tests today to check if this is the case or not.

**Comment by ykuijs** [comment]
When running the New-SPWebApplication twice with the ApplicationPoolAccount parameter, I receive the following error:
`New-SPWebApplication : ApplicationPool exists, either specify an existing ApplicationPool alone, or specify a non existing ApplicatioPool and an ApplicationPoolAccount.`

When removing the ApplicationPoolAccount parameter, the command runs just fine. So we need this check in here to fix the issue @alarzi has mentioned. I will pick up this issue!

Another issue I noticed: The ApplicationPoolAccount parameter is accepting an Managed Account, but we do not check if the managed account exists. The New-SPWebApplication cmdlet fails if the account hasn't been added as a managed account. We have two options:

1. Checking if the managed account exists and if not, throw an error
2. Checking if the managed account exists and if not, create it

Since we already have a xSPManagedAccount resource, I would suggest to do the first option and in the error message specify that the user needs to add the account via xSPManagedAccount first.

**Comment by BrianFarnhill** [comment]
@ykuijs Agree with you and think approach number 1 is what we should do, I dont want to create managed accounts outside of the resource for it. I'll review your PR shortly.

**Comment by BrianFarnhill** [comment]
This fix just got merged in to dev, happy to close this one off now. Thanks guys
