### ISSUE TITLE
PowerShell prerequisite

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/xSharePoint#50]
Hi guys,

What about making the /PowerShell param optional for the offline prerequisites installer. Most installations nowadays will be done on Windows Server 2012 or R2, so it seems overkill to have it mandatory.

**Comment by BrianFarnhill** [comment]
Hi Nik - as part of the DSC resources we just have to follow what the prerequisite installer does, and since it needs to support 2008 R2 then it has to have that option in there. In future versions of the product that don't need to support those operating systems we are likely to see that drop off and change, but for now there isn't much we can do with it.
