### ISSUE TITLE
Endless Reboot Loop using Windows Server Technical Preview 2

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/xSharePoint#52]
I know Win Server 2016 is not supporting SP 2013 just yet, however, trying to troubleshoot my other issue with the DSC resource (https://github.com/PowerShell/xSharePoint/issues/51), I wanted to make sure I tested with WMF 5 and decided to use Server 2016. My current configuration is that I have a DSC pull server running on Windows Server Technical Preview 2, as well as my server node, running the same version of the server OS. Using a DSc config script that worked when my node was Server 2012 R2, now causes an infinite reboot loop when trying to install the prerequisites. I am trying to look at the event viewer to see the root cause of the issue, but it reboots too quick for me to even take a look at it. I will continue to investigate and post my updates using this issue entry.

**Comment by BrianFarnhill** [comment]
Hey Nik. This is by design I suspect. The prereq installer does things differently based on operating system and at the moment we have only tested things on Server 2012 R2. So our scripts for the prereq installer only look for the prereqs that are applied to that OS. What needs to be done here (and I was planning on looking at if/when we add support for that) is putting better detection of what prereqs are needed in to the get and test methods of the prereq installer DSC resource. 

The reason for the loop here is that the test is failing because its not finding all of the prereqs it thinks it needs (based on 2012 R2) and then it calls the set, which runs the prereq installer and it will install what it knows it needs to install the binaries. That then returns the "I completed now reboot me message" and after the reboot it then fails the test method again.

Based on the fact that we don't support server 10 yet though this one is 'by design' and as such we wont look at getting it fixed at this time. That said, if you want to fork the repo and start touching up the prereqs module so its ready to contribute if/when that support is added, then that would be awesome.

**Comment by HiltonGiesenow** [comment]
Hey Brian,

I'm experiencing this today with a Server 2012 R2 machine, with WMF5 PP installed. Will keep you posted if I find anything though. Any thoughts/suggestions?

**Comment by NikCharlebois** [comment]
As an update, this is also still happening with Windows Server 2016 TP4 in Azure

**Comment by BrianFarnhill** [comment]
@NikCharlebois - thanks for the update. We still haven't gone near server 2016 yet because we aren't sure when support will be added to SharePoint for this. Once it is, we'll get it built in but at the moment I can definitely say that the prereq installer will get stuck because the windows features on that OS will be different to what we expect on 2012R2

**Comment by jpalo** [comment]
Well, I get this issue on 2 out of 9 WS2012R2 servers when trying to set up SHarePoint HA farm. The ones in boot loop are not even SharePoint boxes, but one is AD2 and other is SQL2, so I'm guessing this is some bit more generic issue.

**Comment by BrianFarnhill** [comment]
@jpalo DSC resources are able to flag within them that a server needs a reboot, so if you are seeing this reboot, there will be a specific resource you are using on those servers which is indicating that it needs a reboot. If it is doing that in a loop, then we need to raise this as a bug with the appropriate resource to be fixed like we did for the prereq installer resource we have in xSharePoint
