### ISSUE TITLE
xSPInstall requires PID

### ISSUE THREAD

**Issue by craig-martin** [PowerShell/xSharePoint#81]
I was hoping to use xSPInstall to install SharePoint Foundation 2013, but will have to mark the PID property as not mandatory.  Workaround is to use the Package resource, like this:
```
Package InstallSharePointFoundation
{
    Ensure             = "Present"
    Name               = "Microsoft SharePoint Foundation 2013 Core"
    Path               = "E:\SharePoint2013\Setup.exe"
    Arguments          = "/config E:\SharePoint2013\files\setupfarmsilent\config.xml"
    ProductID          = "90150000-1014-0000-1000-0000000FF1CE"
    ReturnCode         = 0
}
```

**Comment by BrianFarnhill** [comment]
Hey @craig-martin - thanks for the workaround. We hadn't tested with SharePoint Foundation, we might add this workaround to the wiki page for the time being until we can make a change to support the install of SP foundation. Thanks for the feedback

**Comment by BrianFarnhill** [comment]
The [wiki documentation](https://github.com/PowerShell/xSharePoint/wiki/xSPInstall) has now been updated to include this work around, we'll leave this on the bug list to be addressed later though. Thanks Craig.

**Comment by BrianFarnhill** [comment]
Reviewing the backlog and coming back to this one - since we have a work around that is in our documentation for SharePoint 2013 and there will be [no SharePoint Foundation in 2016](https://technet.microsoft.com/en-us/library/mt346112%28v=office.16%29.aspx) I'm inclined to close this one off and use the Package resource as the mechanism of installing SharePoint Foundation.
